### ISSUE TITLE
Instalaltion instructions unclear regarding root privileges

### ISSUE THREAD

**Issue by snesbittsea** [example42/psick#107]
It would be helpful if the installation instructions included indication of which commands require root privileges (which I think may be all of them).

**Comment by alvagante** [comment]
Good point, actually most of the commands can be and should be run as unprivileged users, but the ones which install packages (setup.sh...) or need to modify some root owned files.
Will keep this open until docs are updated.

**Comment by snesbittsea** [comment]
Thanks!

In general I have two  concerns when running installation/setup scripts
with root.

   1. Will it result in files/directories in my $HOME environment owned by
   root?
   2. Will it corrupt or interfere with mechanisms like python virtual
   environments, ruby rbenv/rnv or java sdkman.


Bottom line, IMO setup and installation scripts need to be pretty fine
grained so as to ensure the developer can maintain his/her environment.

-steve

**Comment by alvagante** [comment]
Give a look to the linked commit, do you think is it clear ?
The script requiring root are basically only the install and setup ones, so I added sudo where needed in docs or in the same setup.sh.
All the other scripts are supposed to be executed as normal users.

**Comment by snesbittsea** [comment]
Looks good. Thanks!
