### ISSUE TITLE
Unit tests for profile module are failing

### ISSUE THREAD

**Issue by snesbittsea** [example42/psick#116]
At least two problems here.

1. Common.yaml does not contain an entry for profile::base::linux::limits_class 

2. profile::hosts::file fails to compile with an undefined valued for variable ipaddress => Evaluation Error: Error while evaluating a Function Call, Class[Profile::Hosts::File]: parameter 'ipaddress' expects a String value, got Undef at /home/FUZZBUTT/snesbitt/projects/puppet/control-repo/psick/site/profile/spec/fixtures/modules/profile/manifests/base/linux.pp:110:5 on node loki.samdom.aussieswithtails.fuzzbutt

Also, in the profile common.yaml is there any reason not to sort the entries within a section. That is, within the profile::base::linux section, have the variables in sort order. Picky yes, but it can help on the debugging. I'll be glad to do it as part of my general work

-steve

**Comment by snesbittsea** [comment]
Basic problem appears to be that profile::hosts::file expects to be set $::profile::settings::primary_ip and not be undef. But there is no guarantee that the profile::settings class is processed.

**Comment by alvagante** [comment]
Actually profile::settings should be included in manifest/site.pp as a prerequisite.

**Comment by snesbittsea** [comment]
Do you want me to put in a pull request?

**Comment by snesbittsea** [comment]
Hmm...

Ok, a couple of issues here. First, the fixtures/manifests/site.pp is out-of-date and doesn't match the site/manifests/site.pp

Second, there is a bug (https://github.com/rodjek/rspec-puppet/issues/322) in rspec-puppet that under puppet 4.x prevents site.pp from being processed. It does look like a fix has been merged in, but obviously my version of rspec-puppet doesn't contain the fix.

I modified the profile Gem file to pick up the latest rspec-puppet from github and if the existing fixtures/manifests/site.pp is replaced by the manifests/site.pp good things happen.

I'm thinking that the best solution to #2 is to symlink in the canonical site.pp into the fixtures/manifests directory using the .fixtures.yml. That way you don't have to maintain two identical copies of site.pp.

Also, part of what I am working on is updating the profile Gemfile to bring it more inline with what I understand are best practices/standards. I'll have a pull request for you - if you want it - in a week or so.

**Comment by snesbittsea** [comment]
Damn - didn't mean to close it :-)

**Comment by tuxmea** [comment]
@snesbittsea we had a PR a couple of days ago bringing acceptance tests. There is now one PR open bringing host tests. Does this solve this issue?

**Comment by tuxmea** [comment]
@snesbittsea can you please check whether this issue is still open when using latest development or production branch?

**Comment by alvagante** [comment]
All tests ok now
