### ISSUE TITLE
apt module missing with vagrant

### ISSUE THREAD

**Issue by antgel** [example42/psick#145]
Trying to bring up a master with guides like [this](https://github.com/example42/psick/blob/production/docs/FOSS_puppet_server.md) or [that](https://www.example42.com/2017/05/22/automated-puppet-infrastructure-setup/) fails due to:

> Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::apt for ubuntu-xenial at /home/ubuntu/src/git/psick/environments/production/modules/postgresql/manifests/repo/apt_postgresql_org.pp:3:3 on node ubuntu-xenial

I note issue #86 mentions the same thing, and it was closed because @alvagante said: "there should no need of puppetlabs-apt". But apparently there is. My environment is pretty familiar, just following the guides linked.

**Comment by alvagante** [comment]
So, the quick way, for you to fix this, is to add to your Puppetfile the following line

mod 'puppetlabs/apt', :latest

we will probably have to do the same of Psick's Puppetfile, at least commented and properly explained.

**Comment by antgel** [comment]
Sure, I'd have sent a pull request, but the last one was closed. I can submit one, it's just a one-liner (but you might write a better comment ;)). Let me know what you think.

**Comment by alvagante** [comment]
Fix for this should be here: https://github.com/example42/psick/pull/144
