### ISSUE TITLE
Setting memory usage for FOSS Puppet master

### ISSUE THREAD

**Issue by antgel** [example42/psick#147]
I note that by default, `/etc/default/puppetserver` contains:
`JAVA_ARGS="-Xms2g -Xmx2g -XX:MaxPermSize=256m"`

But 2GB is quite big for... Well, a lightly-used server. :)

It would be great if psick provided a way to reduce the memory usage. Any chance of that happening?

**Comment by tuxmea** [comment]
2 GB is the default value, which must be increased on puppet servers with more agents. see https://docs.puppet.com/puppetserver/latest/tuning_guide.html
We could (after initial installation) reduce the number of max instances (each instance needs 512 MB RAM). But initially we need the 2 GB heap.

**Comment by antgel** [comment]
Yes, that's the link that brought me here. If you're saying that going down to 512MB won't work (I was hoping otherwise), I guess this ticket may as well be closed. :)

**Comment by tuxmea** [comment]
512 MB hardly works at all. Usually puppet recommends 6 GB RAM for a production puppetserver with PuppetDB and 3-4 GB RAM for low performance puppetservers. -> Closing. Please feel free to reopen if required.

**Comment by alvagante** [comment]
Whatever could be a default settings, I think we should allow the customisation of the parameter (I would use an template+options_hash approach, setting the default in a $default_hash to merge with users' $options
