### ISSUE TITLE
Gem::DependencyError semantic_puppet

### ISSUE THREAD

**Issue by MSchietzsch** [example42/psick#186]
Just did a quick and dirty install test on an CeontOS 7 running on aws and got to a dependency problem while running
bin/puppet_setup.sh 

[root@ip-10-0-0-120 psick]# gem install r10k
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: r10k requires semantic_puppet (~> 0.1.0); puppet_forge requires semantic_puppet (~> 1.0)

Not sure how much you can do about it, just wanted to let you know. 
I should have run it against the current version (43d358b )

Best Regards
Michael

**Comment by lesinigo** [comment]
there's a dependency conflict in the currently published gems when doing new installs: [r10k-2.5.5 wants puppet_forge ~> 2.2](https://rubygems.org/gems/r10k/versions/2.5.5) and that will bring in [puppet_forge-2.2.7](https://rubygems.org/gems/puppet_forge/versions/2.2.7).

Problem is, r10k-2.5.5 wants `semantic_puppet ~> 0.1` while puppet_forge-2.2.7 wants `semantic_puppet ~> 1.0`, so the whole thing blows up.

As a workaround you should be able to go back at puppet_forge-2.2.6:
```
gem uninstall puppet_forge
gem install puppet_forge -v 2.2.6
```

This thing will probably get fixed once and for all when r10k will depend on a newer semantic_puppet, see https://github.com/puppetlabs/r10k/issues/752

**Comment by MSchietzsch** [comment]
Thank you that workaround helped!

**Comment by tuxmea** [comment]
Note: this is also related to the ruby version used.
Usually you will have an outdated system ruby.
If you have puppet-agent already installed you can also run
```
/opt/puppetlabs/puppet/bin/gem  install r10k
```
