### ISSUE TITLE
Minimal control repo doesn't work

### ISSUE THREAD

**Issue by antgel** [example42/psick#201]
I get the following error:
```
# Copying a minimal control-repo into /home/antony/src/git/psick-test
rsync: change_dir "/home/antony/src/git/psick-munged/docs/skeleton_minimal" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
```
(But psick create carries on, of course there's nothing in the destination, but the output suggests all went fine (apart from the above)).

**Comment by alvagante** [comment]
Linked commit fixes. Thanks for these issues, we need to polish things around and feedback is essential for that 👍

**Comment by antgel** [comment]
My pleasure, thanks for being so responsive. :)
