### ISSUE TITLE
Use pdk in CI

### ISSUE THREAD

**Issue by alvagante** [example42/psick#230]

**Comment by bittner** [comment]
You may want to get inspired by [puppet-software](https://github.com/comsolit/puppet-software/blob/2a6e33aedf44d70b9414a5bad0e84da7ff01c6de/.travis.yml) ([PR #15](https://github.com/edestecd/puppet-software/pull/15)).

In addition, the PDK is available from [package manager repos](https://puppet.com/docs/pdk/1.3/pdk_install.html#install-pdk-on-linux), finally, but it's still somewhat complicated to use that option: You have to choose between Puppet 4 and Puppet 5.

**Comment by alvagante** [comment]
Plan is to use the same tools/commands in different CI/CD tools (Jenkins, GitLab, Travis, Puppet Pipelines), in some cases we can expect pdk to be already installed (via Puppet), so I had waited for the repos availability to start to use pdk for this (having already other scripts doing the same this is/was not a priority)

**Comment by alvagante** [comment]
PDK added to travis ci.
Still not added for the moment to Jenkinsfile and gitlab-ci.yaml.
Closing issue.
