### ISSUE TITLE
puppet_install.sh not working  on fedora 27

### ISSUE THREAD

**Issue by AlessandroLorenzi** [example42/psick#238]
## Expected Behavior 
`bin/puppet_install.sh` installs puppet and stuff

## Actual Behavior
Don't recognize operating system

## Steps to Reproduce the Problem

  1.  run `./bin/puppet_install.sh` as root
```
[...]
### Detected Linux distro: fedorarelease version 27 on arch 64 ###
Not supported distro: fedorarelease
[...]
```

## Specifications

OS: fedora 27

**Comment by alvagante** [comment]
Fix was merged time ago
