### ISSUE TITLE
all_roles task missing

### ISSUE THREAD

**Issue by cdenneen** [example42/psick#260]
Using the Rakefile I have tasks for each role but not an all_roles to run them all:

```
rake beaker_roles:dynatrace                            # Run RSpec code examples
rake beaker_roles:sensu_client                         # Run RSpec code examples
rake beaker_roles:sensu_server                         # Run RSpec code examples
rake beaker_roles:sensu_server_enterprise              # Run RSpec code examples
```

CC @tuxmea 

would be useful to have:
- [x] all_roles
`rake beaker_roles:all_roles` for running all in parallel
- [ ] list/array
`rake beaker_roles:dynatrace,sensu_server_enterprise` for running select roles in parallel

**Comment by tuxmea** [comment]
all_roles is already in production branch

**Comment by cdenneen** [comment]
@tuxmea it's not documented in Rakefile that's why `rake -T` does not show it so `production` needs to be updated to fix that. 
I did verify it does work even though not documented. 

Thanks
