### ISSUE TITLE
Rename Gitlab CI variable CI_BUILD_REF_NAME -> CI_COMMIT_REF_NAME

### ISSUE THREAD

**Issue by karolisc** [example42/psick#273]
Gitlab CI variable `CI_BUILD_REF_NAME` is deprecated. Rename it to `CI_COMMIT_REF_NAME` as in future releases  it will be removed.

> Note: Starting with GitLab 9.0, we have deprecated the $CI_BUILD_* variables. You are strongly advised to use the new variables as we will remove the old ones in future GitLab releases.

Reference:  
https://docs.gitlab.com/ee/ci/variables/#gitlab-90-renaming

Affected files:   
psick\.gitlab-ci.yml
psick\gitlab\.gitlab-ci.yml-integration
psick\gitlab\.gitlab-ci.yml-with-fakes

**Comment by tuxmea** [comment]
@alvagante which version of gitlab are we running internally? Can we just change all occurrences of the deprecated variable to the new one?

**Comment by alvagante** [comment]
@tuxmea yes, we use the latests

**Comment by alvagante** [comment]
Occurrences removed also from also gitlab-ci.yaml files in https://github.com/example42/psick/commit/2d1bd46f550595e5b85ea2ef7c58ce2c945bd877 closing the ticket

**Comment by BaseMax** [comment]
thanks
