### ISSUE TITLE
explore usage of overcommit

### ISSUE THREAD

**Issue by logicminds** [example42/psick#70]
I have used overcommit in other projects to control my hook integration.  Whats great is that you can just drop support into the repo with a `.overcommit.yaml` file.

I think this is better than telling them what hooks to setup by providing a universal file for everyone to use.

https://github.com/brigade/overcommit/

**Comment by alvagante** [comment]
Looks interesting, in the logic of the control-repo that more is better than less, I'd welcome such an addition.

**Comment by logicminds** [comment]
I can make a example repo with overcommit.  But this file would belong in the skeleton dir and other areas depending on what is being validated (Puppetfile, hieradata, ruby)

**Comment by alvagante** [comment]
@logicminds hei, this ticket is a bit abandoned to itself. If you have a nice .overcommit.yaml to suggest and PR for the control-repo that would be very welcomed (could be alternative or replacement for the bin/git_install_hooks.sh script, otherwise let's close this ticket :-)

**Comment by tuxmea** [comment]
@logicminds @alvagante is this ticket still needed open?

**Comment by tuxmea** [comment]
Last ping. Is this something we need and want?

**Comment by logicminds** [comment]
Please close.  Overcommit can sometimes be overly annoying.

On Sep 4, 2017 11:38 AM, "Martin Alfke" <notifications@github.com> wrote:

Last ping. Is this something we need and want?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/example42/psick/issues/70#issuecomment-327013524>, or mute
the thread
