### ISSUE TITLE
MoudleSync/Gemfile Question

### ISSUE THREAD

**Issue by snesbittsea** [example42/psick#97]
I'm starting to work on acceptance tests for the profile module and the Gem file in site/profile is marked as derived from puppetlabs-ntp. Looking at the ntp module I see that I discovered that the Gem file structure is based on ModuleSync which does not appear to be implemented in psick. Should ModuleSync be implemented or should I pull the ModuleSync specific bits out?

Thx,

-steve

**Comment by alvagante** [comment]
Yes, as a general rule any prominent or useful Puppet related software has its place on psick.
Yet I'm not sure on what actually might mean implementing Modulesync here, as we have only two local modules.

**Comment by DavidS** [comment]
Also note that modulesync is used by voxpupuli, and the supported modules,
but is on its way out. We're planning to build an alternative workflow &
tool that'll be less hassle and applicable from your first module. So if
you're currently not aching for modulesync capabilities, you might want to
hold off for another month or two.

**Comment by alvagante** [comment]
Good to know. I'm not sure of the possible integrations that can be done in Psick, but I'm open to any, both via module-sync or new tools

**Comment by DavidS** [comment]
I'll make sure to share what I can, as soon as I can. Currently this is
blocked on renaming the repo and contents from our internal working title
to the "official" one :-D

**Comment by snesbittsea** [comment]
Given that ModuleSync is being phased out and is not implemented in Psick I'd like to remove ModuleSync specific bits as part of my work. Let me know otherwise.

-steve
